// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// set_num_of_threads
bool set_num_of_threads(unsigned int threads);
RcppExport SEXP _MJMrss_set_num_of_threads(SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(set_num_of_threads(threads));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_master();

static const R_CallMethodDef CallEntries[] = {
    {"_MJMrss_set_num_of_threads", (DL_FUNC) &_MJMrss_set_num_of_threads, 1},
    {"_rcpp_module_boot_master", (DL_FUNC) &_rcpp_module_boot_master, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MJMrss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
