# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Rcpp_ModelTransient
#' @aliases ModelTransient
#' @aliases Rcpp_ModelTransient-class
#' @rdname ModelTransient-class
#' @title ModelTransient Class
#' @description Internal representation for multi-server job model with random speed scaling for transient analysis.
#' @slot h - Returns current step size.
#' @slot mean_clients.
#' \itemize{
#' \item Parameter: max_time - maximum time for which you want to calculate mean customers in system;
#' \item Parameter: pi_0 - list of vectors contains distribution at zero time.
#' \item Returns: mean clients in system.
#' }
#' @slot mean_queue
#' \itemize{
#' \item Parameter: max_time - maximum time for which you want to calculate mean queue length;
#' \item Parameter: pi_0 - list of vectors contains distribution at zero time.
#' \item Returns: mean queue length
#' }
#' @slot distribution 
#' \itemize{
#' \item Parameter: max_time - maximum level for which you want to calculate distribution;
#' \item Parameter: pi_0 - list of vectors contains distribution at zero time.
#' \item Returns: list of lists of vectors containing transient distribution.
#' }
#' @examples
#' # M/M/1 model
#' lambda = 1.5
#' mu = 2
#' t = 80
#' library(MJMrss)
#' N = 1 # Number of servers
#' f = c(mu) # Speed (frequency)
#' P_a = matrix(c(1), nrow = 1, byrow = TRUE)
#' P_d = matrix(c(1), nrow = 1, byrow = TRUE)
#' classes = matrix(c(1,# j  
#'                    1,# p_j
#'                    1), # mu_j
#'                  nrow = 3, byrow = TRUE)
#' # use 2 threads for computatuion
#' set_num_of_threads(2)
#' m = build_model(lambda, N, classes, f, P_a, P_d)
#' trans = m$transient_analysis(10, -1)
#' # At zero time in system 3 clients:
#' cl = trans$mean_clients(t, list(c(0),c(0),c(0),c(1)))
#' plot((1:length(cl)-1)*trans$h, cl)
#' \dontrun{
#' library(queueing)
#' i_mm1 <- NewInput.MM1(lambda, mu)
#' o_mm1 <- QueueingModel(i_mm1)
#' L(o_mm1)
#' }
NULL

#' @name Rcpp_ModelTransient$distribution
#' @aliases ModelTransient$distribution
#' @aliases Rcpp_ModelTransient-class$distribution
#' @title Transient distribution
#' @param max_time A maximum time for which you want to calculate mean customers in system;
#' @param pi_0 A list of vectors contains distribution at zero time.
#' @return A list of lists of vectors containing transient distribution at times proportional to the step length h.
NULL

#' @name Rcpp_ModelTransient$mean_queue
#' @aliases ModelTransient$mean_queue
#' @aliases Rcpp_ModelTransient-class$mean_queue
#' @title Mean queue length
#' @param max_time A maximum time for which you want to calculate mean customers in system;
#' @param pi_0 A list of vectors contains distribution at zero time.
#' @return A vector contains mean queue length at times proportional to the step length h.
NULL

#' @name Rcpp_ModelTransient$mean_clients
#' @aliases ModelTransient$mean_clients
#' @aliases Rcpp_ModelTransient-class$mean_clients
#' @title Mean customers in system
#' @param max_time A maximum time for which you want to calculate mean customers in system;
#' @param pi_0 A list of vectors contains distribution at zero time.
#' @return A vector contains mean clients in system at times proportional to the step length h.
NULL

#' @name Rcpp_Model
#' @aliases Model
#' @aliases Rcpp_Model-class
#' @rdname Model-class
#' @title Model Class
#' @description Internal representation for multi-server job model with random speed scaling.
#' @slot rho Returns rho computated by using Neuts ergodicity criteria.
#' @slot mean_clients Returns mean clients in system.
#' @slot mean_queue Returns mean queue length.
#' @slot sum_pi_from_c_to_inf Returns sum of distribution vectors from level N to infinity level.
#' @slot pi_0_c Returns distribution for first N levels.
#' @slot distribution 
#' \itemize{
#' \item Parameter: max_level - maximum level for which you want to calculate distribution;
#' \item Returns: list of vectors containing stationary distribution.
#' }
#' @slot level_description 
#' \itemize{
#' \item Parameter: level -  level for which you want to get a description;
#' \item Returns: human-readable description of level in form "m|s_1,s_2,..." where "m" is a speed mode and "s_i" is
#' a number of serviced customers of "i" class.
#' }
#' @slot level_busy_servers 
#' \itemize{
#' \item Parameter: level -  level for which you want to get a description;
#' \item Returns: vector of numbers of busy servers for each state at specified level.
#' }
#' @slot level_serviced_clients 
#' \itemize{
#' \item Parameter: level -  level for which you want to get a description;
#' \item Returns: vector of numbers of serviced clients for each state at specified level.
#' }
#' @slot transient_analysis 
#' \itemize{
#' \item Parameter: order - numerical order of Taylor series method
#' \item Parameter: stepsize - If positive, then  step length of the algorithm. If negative - the multiplier of the 
#' maximum step of the algorithm.
#' \item Returns: internal representation for model transient analysis (ModelTransient class).
#' }
NULL

#' @name Rcpp_Model$transient_analysis
#' @aliases Model$transient_analysis
#' @aliases Rcpp_Model-class$transient_analysis
#' @title Transient analysis
#' @param order A numerical order of Taylor series method.
#' @param stepsize If positive, then  step length of the algorithm. If negative - the multiplier of the 
#' maximum step of the algorithm
#' @return An internal representation for model transient analysis (ModelTransient class)
NULL

#' @name Rcpp_Model$level_serviced_clients
#' @aliases Model$level_serviced_clients
#' @aliases Rcpp_Model-class$level_serviced_clients
#' @title Serviced clients
#' @param level A level for which you want to get a description;
#' @return A vector of numbers of serviced clients for each state at specified level.
NULL

#' @name Rcpp_Model$level_busy_servers
#' @aliases Model$level_busy_servers
#' @aliases Rcpp_Model-class$level_busy_servers
#' @title Busy servers for level
#' @param level A level for which you want to get a description;
#' @return A vector of numbers of busy servers for each state at specified level.
NULL

#' @name Rcpp_Model$level_description
#' @aliases Model$level_description
#' @aliases Rcpp_Model-class$level_description
#' @title Human-readeble level description
#' @param level A level for which you want to get a description;
#' @return A human-readable description of level in form "m|s_1,s_2,..." where "m" is a speed mode and "s_i" is
#' a number of serviced customers of "i" class
NULL

#' @name Rcpp_Model$distribution
#' @aliases Model$distribution
#' @aliases Rcpp_Model-class$distribution
#' @title Calculate stationary distribution
#' @param max_level A maximum level for which you want to calculate distribution.
#' @return A list of vectors containing stationary distribution.
NULL

#' @name set_num_of_threads
#' @export set_num_of_threads
#' @title set_num_of_threads
#' @description Set number of threads. Works only if OpenMP is enabled. Max number of threads restricted by your CPU
#' @param threads OpenMP only: number of threads for computation.
#' @return TRUE, if OpenMP is enabled, FALSE otherwise.
set_num_of_threads <- function(threads) {
    .Call(`_MJMrss_set_num_of_threads`, threads)
}

